spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_DB:offnanceapplication}?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USR:root}
    password: ${DB_PASS:}
    
configs:
  security:
    authentication:
      jwt:
        app-authorization: ${APP_AUTHORIZATION:Offnance}
        header: ${JWT_HEADER:Authorization}
        expires-in : ${JWT_EXPIRES_IN:600}
        cookie: ${JWT_COOKIE:AUTH-TOKEN}
