spring:
  datasource:
    #url: jdbc:mysql://localhost:3307/offnanceapplication?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    url: ${DB_URL:}

    #username: root
    username: ${DB_USERNAME:}

   #password:
    password: ${DB_PASSWORD:}

configs:
  security:
    authentication:
      jwt:
        app-authorization: ${APP_AUTHORIZATION:Offnance}
        header: ${JWT_HEADER:Authorization}
        expires-in : ${JWT_EXPIRES_IN:600}
        cookie: ${JWT_COOKIE:AUTH-TOKEN}