spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_DB:offnanceapplication}}?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USR:root}
    password: ${DB_PASS:}
    hikari:
      minimum-idle: ${HIKARI_MIN_IDLE:2}
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:8}

configs:
  security:
    authentication:
      jwt:
        app-authorization: ${APP_AUTHORIZATION:Offnance}
        header: ${JWT_HEADER:Authorization}
        expires-in : ${JWT_EXPIRES_IN:600}
        cookie: ${JWT_COOKIE:AUTH-TOKEN}