ALTER TABLE dados ADD ver_dad INT(11) NOT NULL DEFAULT 1;
ALTER TABLE dados ADD cre_at_dad DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dados ADD upd_at_dad DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dados  DROP COLUMN dat_dad;