DROP TABLE tag_texto;

CREATE TABLE IF NOT EXISTS texto(
id_tex BIGINT(20) NOT NULL AUTO_INCREMENT,
tex_tex VARCHAR(500),
ver_tex INT(11) NOT NULL DEFAULT 1,
cre_at_tex DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
upd_at_tex DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT pk_tag_texto PRIMARY KEY(id_tex)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS tag_texto(
id_tex BIGINT(20)NOT NULL,
id_tag BIGINT(20)NOT NULL,
CONSTRAINT pk_tag_texto PRIMARY KEY (id_tag, id_tex),
CONSTRAINT fk_tag_texto_tag FOREIGN KEY(id_tag) REFERENCES tags(id_tag),
CONSTRAINT fk_tag_texto_texto FOREIGN KEY(id_tex) REFERENCES texto(id_tex)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;