
ALTER TABLE tags ADD ver_tag INT(11) NOT NULL DEFAULT 1;
ALTER TABLE tags ADD cre_at_tag DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tags ADD upd_at_tag DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;